### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by ebasatemesgen** [integeruser/GA3C-cpp#3]
I keep getting the error below when I tried to run the bin/GA3C-cartpole-v0. Can you please help me fix this issue. Thank you!

File "third-party/gym-uds-api/gym-uds-server.py", line 70, in <module>
Traceback (most recent call last):
    env.run()
  File "third-party/gym-uds-api/gym-uds-server.py", line 70, in <module>
  File "third-party/gym-uds-api/gym-uds-server.py", line 21, in run
    request = utils.recv_message(self.sock, gym_uds_pb2.Request)
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 14, in recv_message
    message_len = int.from_bytes(recv_exactly(sock, 4), byteorder='little')
    env.run()
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 7, in recv_exactly
  File "third-party/gym-uds-api/gym-uds-server.py", line 21, in run
    packet = sock.recv(n - len(data))
ConnectionResetError: [Errno 104] Connection reset by peer
    request = utils.recv_message(self.sock, gym_uds_pb2.Request)
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 14, in recv_message
    message_len = int.from_bytes(recv_exactly(sock, 4), byteorder='little')
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 7, in recv_exactly
    packet = sock.recv(n - len(data))
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "third-party/gym-uds-api/gym-uds-server.py", line 70, in <module>
    env.run()
  File "third-party/gym-uds-api/gym-uds-server.py", line 21, in run
    request = utils.recv_message(self.sock, gym_uds_pb2.Request)
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 14, in recv_message
    message_len = int.from_bytes(recv_exactly(sock, 4), byteorder='little')
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 7, in recv_exactly
    packet = sock.recv(n - len(data))
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
Traceback (most recent call last):
  File "third-party/gym-uds-api/gym-uds-server.py", line 70, in <module>
  File "third-party/gym-uds-api/gym-uds-server.py", line 70, in <module>
    env.run()
    env.run()
  File "third-party/gym-uds-api/gym-uds-server.py", line 21, in run
  File "third-party/gym-uds-api/gym-uds-server.py", line 21, in run
    request = utils.recv_message(self.sock, gym_uds_pb2.Request)
    request = utils.recv_message(self.sock, gym_uds_pb2.Request)
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 14, in recv_message
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 14, in recv_message
    message_len = int.from_bytes(recv_exactly(sock, 4), byteorder='little')
    message_len = int.from_bytes(recv_exactly(sock, 4), byteorder='little')
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 7, in recv_exactly
  File "/home/kbots/eba/GA3C-cpp/cartpole-v0/third-party/gym-uds-api/utils.py", line 7, in recv_exactly
    packet = sock.recv(n - len(data))
    packet = sock.recv(n - len(data))
ConnectionResetError: [Errno 104] Connection reset by peer
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by integeruser** [comment]
Hello, the error is likely caused by old instances of gym-uds servers running in background. Try to execute the provided `stop-gym-uds-servers.sh` script before training.
